// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace back_end.Models;

public partial class SuperUsers
{
    public int SuperUserID { get; set; }

    public string Username { get; set; }

    public string UserPassword { get; set; }
}