// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace back_end.Models;

public partial class ClientsAddresses
{
    public int AddressID { get; set; }

    public int UserID { get; set; }

    public string Province { get; set; }

    public string Canton { get; set; }

    public string District { get; set; }

    public int PostalCode { get; set; }

    public string OtherSigns { get; set; }
}