// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace back_end.Domain;

public partial class ProductsSearchModel
{
    public string Name { get; set; }

    public string Description { get; set; }

    public int Price { get; set; }

    public string BusinessName { get; set; }

    public byte[] ProductImage { get; set; }
}