// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace back_end.Domain;

public partial class Users
{
    public int UserID { get; set; }

    public string UserName { get; set; }

    public string Email { get; set; }

    public string AccountState { get; set; }

    public string Name { get; set; }

    public string LastNames { get; set; }

    public string BusinessName { get; set; }
}