USE LosAgilesDB
GO

CREATE TABLE Orders (
    OrderID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT newid(),
    [Status] VARCHAR(20) NOT NULL DEFAULT 'Draft',
    DeliveryDate DATE,
    CreatedDate DATE,
    ClientID INT NOT NULL FOREIGN KEY REFERENCES Clients(UserID),
    DeliveryAddress INT FOREIGN KEY REFERENCES ClientsAddresses(AddressID)
)
GO

CREATE TABLE OrderProducts (
    ProductID INT NOT NULL FOREIGN KEY REFERENCES Products(ProductID),
    OrderID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Orders(OrderID),
    Ammount INT NOT NULL DEFAULT 0,
    CONSTRAINT PK_OrderProducts PRIMARY KEY (ProductID, OrderID)
)
GO

CREATE TABLE BusinessOrders (
    OrderID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Orders(OrderID),
    BusinessID INT NOT NULL FOREIGN KEY REFERENCES Businesses(BusinessID)
    CONSTRAINT PK_BusinessOrders PRIMARY KEY (OrderID, BusinessID)
)
GO