USE LosAgilesDB
GO

CREATE TABLE Orders (
    OrderID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT newid(),
    [Status] VARCHAR(20) NOT NULL DEFAULT 'Draft',
    DeliveryDate DATE,
    CreatedDate DATE,
    ClientID INT NOT NULL FOREIGN KEY REFERENCES Clients(UserID),
    DeliveryAddress INT FOREIGN KEY REFERENCES ClientsAddresses(AddressID)
)
GO

CREATE TABLE OrderProducts (
    ProductID INT PRIMARY KEY NOT NULL FOREIGN KEY REFERENCES Products(ProductID),
    OrderID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL FOREIGN KEY REFERENCES Orders(OrderID),
    Ammount INT NOT NULL DEFAULT 0
)
GO

CREATE TABLE BusinessOrders (
    OrderID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL FOREIGN KEY REFERENCES Orders(OrderID),
    BusinessID int PRIMARY KEY NOT NULL FOREIGN KEY REFERENCES Businesses(BusinessID)
)
GO