USE LosAgilesDB
GO

ALTER TABLE Orders ADD DeliveryCost DECIMAL(10,2) NOT NULL DEFAULT 0
GO
ALTER TABLE Orders ADD SubtotalCost DECIMAL(10,2) NOT NULL DEFAULT 0
GO
ALTER TABLE Orders ADD TotalCost DECIMAL(10,2) NOT NULL DEFAULT 0
GO